# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05a524eef3f7a1174b0c8a9eeb701fbc5460669f7a35d2f1ceab5091d72b9519964f6259142870b59b3632f033fffac1b8240614ee13ac2fe697455f3debd905

test:
  secret_key_base: 4ba40dd91bdc1b54bc41bddfbd62281afd5ac27d8ad30f72268b29db907b7c011e030e9508a30efe5ac8d80ce973b506c82756058da8bc0134109f14f3d2b477

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
